name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-version: ["1.88.0", "stable"]

    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup install --profile default ${{ matrix.rust-version }}
          rustup default ${{ matrix.rust-version }}

      - name: Check code formatting
        run: cargo fmt --check

      - name: Lint code
        run: cargo clippy --all-targets

      - name: Build
        run: cargo build --all-targets

      - name: Run tests
        run: cargo test

      - name: Generate documentation
        run: cargo doc
