name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check code formatting
        run: cargo fmt --check

      - name: Lint code
        run: cargo clippy --all-targets

      - name: Build
        run: cargo build --all-targets

      - name: Run tests
        run: cargo test

      - name: Generate documentation
        run: cargo doc
